version: '3.9'
services:
  postgres:
    container_name: my_postgres
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   
  nginx:
    container_name: my_nginx
    image: nginx
    volumes: 
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/etc/nginx/html
    ports:
      - 80:80
      - 443:443
      
  redis:
    container_name: my_redis
    image: redis
    command: redis-server --loglevel warning
    ports:
      - 6379:6379

  auth:
    container_name: my_auth
    image: auth_server_image
    ports:
      - 5052:5052

  gateway:
    container_name: my_gateway
    image: gateway_image
    ports:
      - 6433:6433

  
