// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: req_pq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestPqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce     string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MessageId int32  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *RequestPqRequest) Reset() {
	*x = RequestPqRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_pq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPqRequest) ProtoMessage() {}

func (x *RequestPqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_req_pq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPqRequest.ProtoReflect.Descriptor instead.
func (*RequestPqRequest) Descriptor() ([]byte, []int) {
	return file_req_pq_proto_rawDescGZIP(), []int{0}
}

func (x *RequestPqRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *RequestPqRequest) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type RequestPqResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce       string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce string `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	MessageId   int32  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	P           int32  `protobuf:"varint,4,opt,name=p,proto3" json:"p,omitempty"`
	G           int32  `protobuf:"varint,5,opt,name=g,proto3" json:"g,omitempty"`
}

func (x *RequestPqResponse) Reset() {
	*x = RequestPqResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_pq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPqResponse) ProtoMessage() {}

func (x *RequestPqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_req_pq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPqResponse.ProtoReflect.Descriptor instead.
func (*RequestPqResponse) Descriptor() ([]byte, []int) {
	return file_req_pq_proto_rawDescGZIP(), []int{1}
}

func (x *RequestPqResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *RequestPqResponse) GetServerNonce() string {
	if x != nil {
		return x.ServerNonce
	}
	return ""
}

func (x *RequestPqResponse) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *RequestPqResponse) GetP() int32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *RequestPqResponse) GetG() int32 {
	if x != nil {
		return x.G
	}
	return 0
}

var File_req_pq_proto protoreflect.FileDescriptor

var file_req_pq_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x71, 0x5f, 0x70, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x72, 0x65, 0x71, 0x5f, 0x70, 0x71, 0x22, 0x47, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22,
	0x87, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x71, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x0c, 0x0a,
	0x01, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x67, 0x32, 0x52, 0x0a, 0x0c, 0x52, 0x65, 0x71,
	0x50, 0x71, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x71, 0x12, 0x18, 0x2e, 0x72, 0x65, 0x71, 0x5f, 0x70, 0x71, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x72, 0x65, 0x71, 0x5f, 0x70, 0x71, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a,
	0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_req_pq_proto_rawDescOnce sync.Once
	file_req_pq_proto_rawDescData = file_req_pq_proto_rawDesc
)

func file_req_pq_proto_rawDescGZIP() []byte {
	file_req_pq_proto_rawDescOnce.Do(func() {
		file_req_pq_proto_rawDescData = protoimpl.X.CompressGZIP(file_req_pq_proto_rawDescData)
	})
	return file_req_pq_proto_rawDescData
}

var file_req_pq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_req_pq_proto_goTypes = []interface{}{
	(*RequestPqRequest)(nil),  // 0: req_pq.RequestPqRequest
	(*RequestPqResponse)(nil), // 1: req_pq.RequestPqResponse
}
var file_req_pq_proto_depIdxs = []int32{
	0, // 0: req_pq.ReqPqService.RequestPq:input_type -> req_pq.RequestPqRequest
	1, // 1: req_pq.ReqPqService.RequestPq:output_type -> req_pq.RequestPqResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_req_pq_proto_init() }
func file_req_pq_proto_init() {
	if File_req_pq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_req_pq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPqRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_req_pq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPqResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_req_pq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_req_pq_proto_goTypes,
		DependencyIndexes: file_req_pq_proto_depIdxs,
		MessageInfos:      file_req_pq_proto_msgTypes,
	}.Build()
	File_req_pq_proto = out.File
	file_req_pq_proto_rawDesc = nil
	file_req_pq_proto_goTypes = nil
	file_req_pq_proto_depIdxs = nil
}
