// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: authz.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthzClient is the client API for Authz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthzClient interface {
	PGAgreement(ctx context.Context, in *PGRequest, opts ...grpc.CallOption) (*PGResponse, error)
	DiffieHellman(ctx context.Context, in *DiffieHellmanRequest, opts ...grpc.CallOption) (*DiffieHellmanResponse, error)
}

type authzClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthzClient(cc grpc.ClientConnInterface) AuthzClient {
	return &authzClient{cc}
}

func (c *authzClient) PGAgreement(ctx context.Context, in *PGRequest, opts ...grpc.CallOption) (*PGResponse, error) {
	out := new(PGResponse)
	err := c.cc.Invoke(ctx, "/authz_client.Authz/PGAgreement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzClient) DiffieHellman(ctx context.Context, in *DiffieHellmanRequest, opts ...grpc.CallOption) (*DiffieHellmanResponse, error) {
	out := new(DiffieHellmanResponse)
	err := c.cc.Invoke(ctx, "/authz_client.Authz/DiffieHellman", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthzServer is the server API for Authz service.
// All implementations must embed UnimplementedAuthzServer
// for forward compatibility
type AuthzServer interface {
	PGAgreement(context.Context, *PGRequest) (*PGResponse, error)
	DiffieHellman(context.Context, *DiffieHellmanRequest) (*DiffieHellmanResponse, error)
	mustEmbedUnimplementedAuthzServer()
}

// UnimplementedAuthzServer must be embedded to have forward compatible implementations.
type UnimplementedAuthzServer struct {
}

func (UnimplementedAuthzServer) PGAgreement(context.Context, *PGRequest) (*PGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PGAgreement not implemented")
}
func (UnimplementedAuthzServer) DiffieHellman(context.Context, *DiffieHellmanRequest) (*DiffieHellmanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiffieHellman not implemented")
}
func (UnimplementedAuthzServer) mustEmbedUnimplementedAuthzServer() {}

// UnsafeAuthzServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthzServer will
// result in compilation errors.
type UnsafeAuthzServer interface {
	mustEmbedUnimplementedAuthzServer()
}

func RegisterAuthzServer(s grpc.ServiceRegistrar, srv AuthzServer) {
	s.RegisterService(&Authz_ServiceDesc, srv)
}

func _Authz_PGAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServer).PGAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authz_client.Authz/PGAgreement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServer).PGAgreement(ctx, req.(*PGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authz_DiffieHellman_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffieHellmanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServer).DiffieHellman(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authz_client.Authz/DiffieHellman",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServer).DiffieHellman(ctx, req.(*DiffieHellmanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authz_ServiceDesc is the grpc.ServiceDesc for Authz service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authz_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authz_client.Authz",
	HandlerType: (*AuthzServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PGAgreement",
			Handler:    _Authz_PGAgreement_Handler,
		},
		{
			MethodName: "DiffieHellman",
			Handler:    _Authz_DiffieHellman_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authz.proto",
}
